name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  country_code_picker: ^3.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets: 
   - assets/
   - assets/google_fonts/
  uses-material-design: true
